refactor: Code cleanup, better variables

diff --git a/bin/shtest b/bin/shtest
--- a/bin/shtest
+++ b/bin/shtest
@@ -1,21 +1,54 @@
 # shellcheck shell=sh
 
-main() {
+__shtest_util_exec_fn() {
+	unset REPLY; REPLY=
+	__shtest_function_name="$1"
+
+	if PATH= command -v "$__shtest_function_name" >/dev/null 2>&1; then
+		if __shtest_function_output="$("$__shtest_function_name" 2>&1)"; then
+			__shtest_function_exitcode="$?"
+		else
+			__shtest_function_exitcode="$?"
+		fi
+
+		printf '%s\n' "$__shtest_function_output" | while IFS= read -r __shtest_line; do
+			printf '# %s\n' "$__shtest_line"
+		done; unset __shtest_line
+	fi
+	REPLY=$__shtest_function_exitcode
+
+	unset __shtest_function_name __shtest_function_exitcode
+}
+
+__shtest_main() {
 	for arg; do case "$arg" in
 	-h|--help)
-		printf '%s\n' "shtest - A POSIX shell test runner
+		printf '%s\n' "Usage:
+   shtest [flags] [test-file] [test-dir]
 
-		Usage:
-		    shtest <test-dir>
-
-		-h|--help
-		    Show help menu"
+Flags:
+   -h, --help
+      Show help menu"
 		return
 		;;
 	esac done
 
 	export TEST_DIR= TEST_FILE= TEST_FUNCTION= TEST_SHELL= SHTEST='yes'
+
+	# for TEST_DIR; do
+
 	TEST_DIR="$1"; shift
+	if [ -z "$TEST_DIR" ]; then
+		printf '%s\n' "Error: shtest: No test directory passed"
+		exit 1
+	elif [ -f "$TEST_DIR" ]; then
+		printf '%s\n' "Error: shtest: Expected a directory, not file '$TEST_DIR'"
+		exit 1
+	elif [ ! -d "$TEST_DIR" ]; then
+		printf '%s\n' "Error: shtest: Cannot find directory at '$TEST_DIR'"
+		exit 1
+	fi
+
 	if ! TEST_DIR="$(
 		if ! CDPATH= cd -P "$TEST_DIR"; then
 			exit 1
@@ -25,14 +58,6 @@ main() {
 		fi
 	)"; then
 		printf '%s\n' "Error: shtest: Could not convert test directory to full path"
-	fi
-
-	if [ -f "$TEST_DIR" ]; then
-		printf '%s\n' "Error: shtest: Expected a directory, not file '$TEST_DIR'"
-		exit 1
-	elif [ ! -d "$TEST_DIR" ]; then
-		printf '%s\n' "Error: shtest: Cannot find directory at '$TEST_DIR'"
-		exit 1
 	fi
 
 	for TEST_FILE in "$TEST_DIR"/*.sh; do
@@ -70,46 +95,35 @@ main() {
 
 		printf '%d..%d\n' '1' "$__shtest_functions_length"
 
-		if PATH= command -v setup_file >/dev/null 2>&1; then
-			setup_file
-		fi
+		__shtest_util_exec_fn 'setup_file'
 
 		__shtest_function_i=1
 		while [ -n "$__shtest_functions" ]; do
 			TEST_FUNCTION="${__shtest_functions%%:*}"
 
-			if PATH= command -v setup >/dev/null 2>&1; then
-				setup
-			fi
+			__shtest_util_exec_fn 'setup'
 
-			__shtest_function_output="$(SHTEST='yes' "$TEST_FUNCTION" 2>&1)"
-			__shtest_function_exitcode=$?
-			printf '%s\n' "$__shtest_function_output" | while IFS= read -r line; do
-				printf '# %s\n' "$line"
-			done; unset line
-
-			if [ $__shtest_function_exitcode -eq 0 ]; then
+			__shtest_util_exec_fn "$TEST_FUNCTION"
+			if [ $REPLY -eq 0 ]; then
 				printf '%s\n' "ok $__shtest_function_i $TEST_FUNCTION"
 			else
 				printf '%s\n' "not ok $__shtest_function_i $TEST_FUNCTION"
 			fi
-			unset __shtest_function_output __shtest_function_exitcode
 
-			if PATH= command -v teardown >/dev/null 2>&1; then
-				teardown
-			fi
+			__shtest_util_exec_fn 'teardown'
 
 			__shtest_function_i=$((__shtest_function_i=__shtest_function_i+1))
 			__shtest_functions="${__shtest_functions#*:}"
 		done
+		unset __shtest_function_i
 
-		if PATH= command -v teardown_file >/dev/null 2>&1; then
-			teardown_file
-		fi
+		__shtest_util_exec_fn 'teardown_file'
 	done; unset TEST_FILE
 
-	unset __shtest_function_i __shtest_functions
+	unset __shtest_functions_length __shtest_functions
+
+	# done
 }
 
 
-LC_ALL=C main "$@"
+LC_ALL=C SHTEST=yes __shtest_main "$@"
